### ISSUE TITLE
Can‘t find this file "apa_plasmid_data.pickle"

### ISSUE THREAD

**Issue by Lsxlsxls** [johli/genesis#1]
Hello,
I want to learn and run your code, but I can't find the data you use, such like
"apa_plasmid_data.pickle", can you tell me where I can find it？Thank you very much.

**Comment by johli** [comment]
Hi,

Sorry for the late reply. .pickle files are not the best to share since they are OS-dependent, so I re-saved the processed data as a .csv file (readable with python package pandas) and a .mat file (readable with scipy.io.loadmat). I have uploaded the data to the google drive and you can find it at the following link: https://drive.google.com/file/d/1NMqA0-xohZ1b2cduENLU8W-idi0KOHQi/view?usp=sharing

Please let me know if you run into any other issues.

Best,

Johannes

**Comment by Lsxlsxls** [comment]
@johli It is a great honor for you to reply to me, I see. thank you very much！
